N, M, L, R = map(int, input().split())
print(N, M, L, R)
cont = 0
cont += (M*(N-1)) + (N*(M-1))
print('Resultado  =', (M*(N-1)) + (N*(M-1)))
print('Contagem  =', cont)
cont += (M-1) * (N*(N-1))
print('Resultado  =', (M-1) * (N*(N-1)))
print('Contagem  =', cont)
cont += (N-1) * ((M*(M-3))+2)
print('Resultado  =', (N-1) * ((M*(M-3))+2))
print('Contagem  =', cont)
